### PR TITLE
Chnage Token to be a public property

### PR DESCRIPTION
**Pull request by saguiitay**

### CODE REVIEW

**Comment by Rambalac** [comment]
Why making it public? It's temporal variable and has no much meaning outside except for saving and restoring

**Comment by saguiitay** [comment]
It's not really temporary. You are supposed to keep the RefreshToken in your app's DB and reuse it the next time the user uses your app, and wants to access Amazon Cloud Drive.
In order to access it, is needs to be public.

**Comment by Rambalac** [comment]
Token is updated automatically and OnTokenUpdated get called with updated tokens

**Comment by saguiitay** [comment]
First, the UpdateToken is only called assuming that the Token was successfully retrieved - it's not called in the case where the Token changed into `null` (because of the fact that the `OnTokenUpdated` event is a `<string, string, DateTime>` handler, and not a `<AuthToken>` handler).

Secondly, it's a somewhat bad pattern to follow - using `OnTokenUpdated` means that the AmazonDrive class holds a reference to the class using it, which is a bad practice. For example, assume I have an `AmazonHelper` class, which uses your AmazonDrive. Now if I want to use the `AmazonHelper` class to authenticate and save the Token from a web Controller, I have 2 options:

  1. Register on the `OnTokenUpdated` in `AmazonHelper`, to catch changes in the Token, update a local Token instance, and expose that Token to the Controller.
  2. Expose a Token property in the AmazonHelper, which just exposes the Token property of the AmazonDrive.

Option 2 is much simpler and clearer.

Events are nice and simple for relatively simple applications, but they don't scale well, and don't play nice with more complex scenarios (IoC, proxies, unit tests, etc.).

**Comment by Rambalac** [comment]
Ok, reference is bad. But how your app is going to understand when token is refreshed?

**Comment by saguiitay** [comment]
That's the app's problem... it'll have to check if the refresh token changed. The same way that ORMs check if an entity was modified....

Anyway, my suggested change doesn't remove the event/handler - it just exposes the Token, yo give more options to the developer.

**Comment by Rambalac** [comment]
Current Token is just JSON class, need proper public getters.
ORM work in opposite way, you provide them your class and say when update.
And if you miss token update next you have to relogin again.

By the way, why do you need to expose Token to the Controller?

**Comment by Rambalac** [comment]
And whole library is not really designed well for multiple accounts

**Comment by Rambalac** [comment]
What about this?
```
private WeakReference<Action<string, string, DateTime>> weakOnTokenUpdate = null;
public Action<string, string, DateTime> OnTokenUpdate
{
    set
    {
        weakOnTokenUpdate = new WeakReference<Action<string, string, DateTime>>(value);
    }
}
```

**Pull request closed without merging**
